name: Docker Build &  Deploy to Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"

  deploy_to_google_cloud:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    needs: [build]
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - run: gcloud container clusters get-credentials ${{secrets.GCP_CLUSTERNAME}} --zone us-central1
      - name: deploy
        run: |

          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
