name: Docker Build Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"

  deploy_to_google_cloud:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: configure docker
        run: gcloud auth configure-docker

      - name: Pull the image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}

      - name: tage image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}

      - name: push image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}

      - name: Deploy
        run: |
          gcloud auth login
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set compute/zone us-central1
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTERNAME }}
          gcloud config set run/cluster_location us-central1
          gcloud config set run/platform gke ${{ secrets.GCP_CLUSTERNAME }}
          gcloud run deploy order-service --image=gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }} --cluster=${{ secrets.GCP_CLUSTERNAME }}
